### PR TITLE
fixed - css libraries importing order

### PR DESCRIPTION
**Pull request by renancouto**
This PR fixes the order of css libraries (Bourbon and Neat) that should be before the `base` files.

### CODE REVIEW

**Comment by maurogeorge** [comment]
Hi @renancouto thanks for your PR.

What you are trying to fix here? Accordingly to the [README](https://github.com/thoughtbot/bitters/blob/master/README.md) on the `5.` at installation section we need to 

>And import Neat after Bitters in your application.css.scss or main manifest file:
>```
>@import "bourbon";
>@import "base/base";
>@import "neat";
>```

And we already uncomment the [file mentioned here](https://github.com/renancouto/pah/blob/fix-css-order/lib/pah/templates/bourbon.rb#L23).

**Comment by renancouto** [comment]
Hey @maurogeorge, this PR doesn't fix anything. I was having a problem on another project and thought that might be the cause. Sorry about that.

Anyways, I think this type of files (a bunch of mixins that doesn't generate any styles by themselves) should be grouped together or even be moved on to another file (ex. `_shared.scss`). This way other files, instead of the main one, could import it and benefit from its libraries too. What do you think?

**Comment by maurogeorge** [comment]
@renancouto I see. I think the better way is to fix the problem in the other project and if the solution is a good one to all new projects we add this on pah. Makes sense?

In fact the bitters generate styles, a base style and it is recommended to the people to edit the `base/base` [files and add new ones accordingly to the need](https://github.com/thoughtbot/bitters#sass-structure--default-style).

I think we can close this PR, makes sense?

**Comment by renancouto** [comment]
Great @maurogeorge! Sure, let's see how this evolves.

**Comment by maurogeorge** [comment]
:+1:

**Pull request closed without merging**
