### PR TITLE
bundle install using the correct rvm environment

### PR DESCRIPTION
**Pull request by marcioj**
At the moment, pah is bundle install'ing and using the default ruby version which the command was started. 
So when you enter into the generated project the console outputs that the gemset is created because the `.ruby-version` and `.ruby-gemset` exist. And then you have to bundle install again to get the dependencies for this new environment.
This PR fixes it manually creating the gemset, *and* running the bundle install using it.

How to test:
```sh
cd path/to/pah
git pull this patch
rvm gemset delete test_pah # delete any previous created gemset
bundle exec ./bin/pah ~/test_pah # run pah using these changes
cd ~/test_pah
rails s # should not claim about missing gems
```

### CODE REVIEW

**Comment by TiuTalk** [comment]
**RVM** is not (and will not be?) a dependency of **pah**.

We have instructions for it on the [RVM section](https://github.com/Helabs/pah#rvm) of the README.

AFAIK, If you follow these instructions, you don't need to `bundle install` twice.

**Comment by maurogeorge** [comment]
I agree with @TiuTalk we dont need to handle RVM, the user can use rbenv or chruby. In the past we handle all rvm, but is kinda a hack changing from env to other.

We have some old issues about it like https://github.com/Helabs/pah/issues/56 https://github.com/Helabs/pah/issues/76 https://github.com/Helabs/pah/issues/73

An example of [old _rvm partial here](https://github.com/Helabs/pah/blob/b37f167d95f2fe9477e2b0173b10a22bf34e5d78/lib/pah/partials/_rvm.rb).

I vote :-1: 
I think the README and wiki is enough.

**Comment by marcioj** [comment]
The readme is wrong, it should be:

```sh
$ rvm use 2.1.5@projectname --create
$ gem install pah
$ pah projectname
````

@maurogeorge what was the problems we hit when trying to handle the rvm stuff? Why this got dropped from pah?

Pah handles a lot of things like: generate a new app, setup the database, create the heroku app using the toolbelt etc, so It's a pretty strange to not handle version managers. 
If we don't want to support any version manager, I suggest remove the `.ruby-version` and `.ruby-gemset` to make more explicit, so I believe that `pah thing` will just work.

Anyway I will use `echo 'export rvm_ignore_gemsets_flag=1' >> $HOME/.rvmrc` for now. But I am concerned for people trying to use this gem and get stuck because these problems.

**Comment by maurogeorge** [comment]
@marcioj I am not really sure the README is wrong, I guess it assumes that you have pah installed global as mentioned [here](https://github.com/Helabs/pah/wiki/Using-Pah-with-RVM).

We dropped the rvm stuff, since we got some headaches, see more on the issues I sent before, and we believe we dont need to handle this, the user can use pah with RVM, rbenv, chruby etc. Like [suspenders](https://github.com/thoughtbot/suspenders) do.

I guess we can keep the `.ruby-*` files, like the [mongoid](https://github.com/mongoid/mongoid) does. You can use your favorite ruby version manager or not at all.

We don`t need to worry with future problems, if anyone got a issue in the future, they tell us and we think on how to fix.

**Comment by marcioj** [comment]
> @marcioj I am not really sure the README is wrong, I guess it assumes that you have pah installed global as mentioned here.
Ok, I sent #458 to centralize the rvm things in the wiki

> We dropped the rvm stuff, since we got some headaches, see more on the issues I sent before, and we believe we dont need to handle this, the user can use pah with RVM, rbenv, chruby etc. Like suspenders do.

I think suspenders just use `.ruby-version`. Pah uses `.ruby-gemset` which causes this issue

> I guess we can keep the .ruby-* files, like the mongoid does. You can use your favorite ruby version manager or not at all.

I believe this is other context, Mongoid will not suffer this problem since it's not bundle install'ing itself

I am ok in drop my changes and not manage any ruby manager.
But I think we need to remove the `.ruby-gemset` to avoid in become [this](https://github.com/Helabs/pah#rvm) the default step. If someone wants it just add by your own, I just want to `pah something` and all works :smile:

**Comment by maurogeorge** [comment]
@marcioj I dont like the idea of drop `.ruby-gemset` since this the way we work on HE:labs, all projects have this file. This way a person can clone the project, bundle and starting coding.

**Comment by maurogeorge** [comment]
@marcioj any feedback on it? What you think about ir @TiuTalk ?

**Comment by maurogeorge** [comment]
@marcioj and I talked about it. And the problem is that pah does the bundle of the project, so when you enter the project folder you need to bundle again, because of the `.ruby-version` and `.ruby-gemset`. So in the future we can make a PR to remove the bundle on the template like the [suspenders](https://github.com/thoughtbot/suspenders/blob/9e56ef12f5ea1e333b8c514d076b834a38febb3e/lib/suspenders/generators/app_generator.rb#L215-L217) does.

Since we have on the README that we need to run the `$ bin/setup`, when running this the bundle is installed.

**Pull request closed without merging**
