### PR TITLE
Remove some spec/support files

### LINKED ISSUE #461: Remove old and unused `spec/support` files
Today on [spec/support](https://github.com/Helabs/pah/tree/5c281f2f7ea299599e809f765e45f314b8fc46c1/lib/pah/files/spec/support) of the generated app we have a lot of old and unused files, like the [matchers](https://github.com/Helabs/pah/blob/5c281f2f7ea299599e809f765e45f314b8fc46c1/lib/pah/files/spec/support/matchers.rb) that define a single matcher that can be substitued by the [respond_with](http://thoughtbot.github.io/shoulda-matchers/v2.7.0/Shoulda/Matchers/ActionController.html#respond_with-instance_method) from the shoulda-matchers that is shipped with pah. We need to track this kinda of old and unused support.

- [ ] Track all files that can be removed
- [ ] Remove these files

### PR DESCRIPTION
**Pull request by maurogeorge**
Closes #461

### CODE REVIEW

**Comment by maurogeorge** [comment]
@TiuTalk @marcioj could you plz review?

**Comment by rodrigopinto** [comment]
@maurogeorge It seems to be ok! Just waiting for new build to merge it!

**Comment by maurogeorge** [comment]
@rodrigopinto thanks for the review :star:

**Comment by rodrigopinto** [comment]
@maurogeorge It was on my plans, I've did it yesterday on a project. :( Thanks for PR.

**Comment by marcioj** [comment]
Burn these files with :fire:

**Pull request merged**
