### PR TITLE
Feature/change ruby and rails version

### LINKED ISSUE #451: Update to Rails 4.2 and Ruby 2.2

### PR DESCRIPTION
**Pull request by guiloyins**
closes #451

### CODE REVIEW

**Comment by guiloyins** [comment]
Github with result: https://github.com/guiloyins/testepah
Heroku project with new version: http://testepah.herokuapp.com/

**Comment by maurogeorge** [comment]
I see some little diferences on the a vanilla Rails app.

- [ ] The `bin/spring` was not generated
- [ ] The `bin/rails`, `bin/rake` is slight different, its not mention spring
- [ ] The `config/application` default has a `require 'rails/all'` on pah we have a `# Pick the frameworks you want:` and some require of railties.
- [ ] On Gemfile `'sass-rails', '~> 5.0'` today we point to github
- [ ] On Gemfile group ":development, :test" add 'byebug', 'web-console', '~> 2.0' and `spring`

**Comment by guiloyins** [comment]
and Travis has failed.

**Comment by TiuTalk** [comment]
Please rebase, @guiloyins

**Comment by guiloyins** [comment]
@TiuTalk  I don't know why I didn't rebase. Anyway, there's another issue with the Canonical Host not being inserted in config.ru. I will check both of them on friday.

**Pull request merged**
