### PR TITLE
[Fix #492] Upgrade rack-timeout version.

### LINKED ISSUE #492: Upgrade rack-timeout to use the heroku version
Today we use a fork https://github.com/kch/rack-timeout, that actually redirect to the heroku gem.

I think we are good to use the heroku gem directly from the rubygems.

I really don't remember why we use a specific hash on the fork. Any idea @tomasmuller @TiuTalk ?

### PR DESCRIPTION
**Pull request by rodrigopinto**
As discussed on #492 we can move forward to use `heroku/rack-timeout` gem. So, I've change the Gemfile configuration to use the latest version of the gem.

### CODE REVIEW

**Comment by rodrigopinto** [comment]
@maurogeorge @thiagogabriel

**Comment by thiagogabriel** [comment]
[rack-timeout sucks with puma](https://github.com/heroku/rack-timeout/issues/73). We had problems with it and we removed from atendesimples. We are still having problems on appraise probably because of it https://github.com/helabs/appraise/issues. @mateusg and I vote to remove it :)

**Comment by mateusg** [comment]
:+1: I vote to remove it too, at least for now. It's quite risky to use it with Puma, specially if your project gems has C bindings.

> Rack-timeout is unable to abort things hung in C land, like a bunch of IO stuff, so that would be my first suspicion. Those requests should eventually time out, raise, and the backtrace might show what was holding the request.

> Yeah it seems rack-timeout and puma don't play nice in many ways. Gotta take some time to investigate that.

https://github.com/heroku/rack-timeout/issues/73#issuecomment-89170627

**Comment by rodrigopinto** [comment]
@thiagogabriel @mateusg Yeah guys, `rack-timeout` don't play nice with Puma, so if we are going to keep Puma the best way is to close this PR and remove `rack-timeout` on a new one.

**Comment by thiagogabriel** [comment]
@rodrigopinto :+1: can you do it now?

**Pull request closed without merging**
