### PR TITLE
Bump ruby to 2.3.0 and rails to 4.2.5.1

### PR DESCRIPTION
**Pull request by hudsonsferreira**

### CODE REVIEW

**Comment by ndrluis** [comment]
:heart: @hudsonsferreira

**Comment by ndrluis** [comment]
@hudsonsferreira to fix specs see https://github.com/Helabs/pah/commit/e34623423ea2662f299d25df6e529dbde437278a

**Comment by ndrluis** [comment]
and remember to update the README and CHANGELOG files

**Comment by eduardofiorezi** [comment]
Closed to wait the next rails 5 release.

**Pull request closed without merging**
